-- Load Q1
LOAD DATA LOCAL INFILE 'data/Divvy_Trips_2019_Q1.csv'
INTO TABLE trips_2019
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load Q2 (Use the FIXED file)
LOAD DATA LOCAL INFILE 'data/Divvy_Trips_2019_Q2_Fixed.csv'
INTO TABLE trips_2019
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load Q3
LOAD DATA LOCAL INFILE 'data/Divvy_Trips_2019_Q3.csv'
INTO TABLE trips_2019
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load Q4
LOAD DATA LOCAL INFILE 'data/Divvy_Trips_2019_Q4.csv'
INTO TABLE trips_2019
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n'
IGNORE 1 ROWS;